
runtime: nodejs20 # Using Node.js runtime to serve static files efficiently

handlers:
  # Serve all static files in the directory
  - url: /
    static_files: index.html
    upload: index.html

  - url: /(.*)
    static_files: \1
    upload: (.*)

# Optional: settings for scaling
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 3
